
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[override]]
  name = "github.com/docker/cli"
  branch = "master"
  source = "github.com/mnottale/cli"

[[constraint]]
  name = "github.com/gotestyourself/gotestyourself"
  branch = "master"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "v1.8.2"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.8.2"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/docker/go-metrics"
  revision = "d466d4f6fd960e01820085bd7e1a24426ee7ef18"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true
