debug: true
mysql:
  image:
    version: 8
  rootpass: axx[<^cz3d.fPb
  database: wordpressdata
  user:
    name: wordpress
    password: wordpress
wordpress:
  scale:
    mode: global
    replicas: 0
volumes:
  db_data:
    name: db_data
