privileged: false
myapp:
  debug: false
  nginx_version: latest
  nginx_replicas: 2
watcher:
  image: watcher:latest
read_only: true
stdin_open: true
tty: true
aport: 10000
sport: 11000
dport: 12000
memory: 100000000
timeout: 10000000000
