version: "3.7"

services:
  rng:
    build: rng
    ports:
      - "${rng.port}:80"

  hasher:
    build: hasher
    ports:
      - "${hasher.port}:80"

  webui:
    build: webui
    ports:
      - "${webui.port}:80"

  redis:
    image: redis

  worker:
    build: worker

